version: '3'
services:
  learn_elixir_graphql_dbserver:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      # default is 32MB;
      - "shared_buffers=128MB"
    volumes:
      - learn_elixir_graphql_dbserver_data:/var/lib/postgresql/data
volumes:
  learn_elixir_graphql_dbserver_data:
